/*
**  Copyright 2022 bitValence, Inc.
**  All Rights Reserved.
**
**  This program is free software; you can modify and/or redistribute it
**  under the terms of the GNU Affero General Public License
**  as published by the Free Software Foundation; version 3 with
**  attribution addendums as found in the LICENSE.txt
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU Affero General Public License for more details.
**
**  Purpose:
**    Implement the Hi_world application
**
**  Notes:
**   1. This file was automatically generated by cFS Basecamp's app
**      creation tool. If you edit it, your changes will be lost if
**      a new app with the same name is created. 
**
*/


/*
** Includes
*/

#include <string.h>
#include "hi_world_app.h"
#include "hi_world_eds_cc.h"
#include "cfe_sb.h" 

/***********************/
/** Macro Definitions **/
/***********************/

/* Convenience macros */
#define  INITBL_OBJ    (&(Hi_world.IniTbl))
#define  CMDMGR_OBJ    (&(Hi_world.CmdMgr))


/*******************************/
/** Local Function Prototypes **/
/*******************************/

static int32 InitApp(void);
static int32 ProcessCommands(void);
static void SendStatusTlm(void);
void  OBDH_Telem_InitUDP(void);
void  OBDH_TC_InitUDP(void);
void ExtractDataFromBuffer(uint8_t *buffer, ssize_t bytes_received);
void SendOBDHCommand(uint16_t payload_value);

static int sock = -1;
static uint16_t setParamTemp = 0xFFFF;
struct sockaddr_in clientAddr;


/**********************/
/** File Global Data **/
/**********************/

/* 
** Must match DECLARE ENUM() declaration in app_cfg.h
** Defines "static INILIB_CfgEnum_t IniCfgEnum"
*/
DEFINE_ENUM(Config,APP_CONFIG)  


/*****************/
/** Global Data **/
/*****************/

HI_WORLD_Class_t  Hi_world;


/******************************************************************************
** Function: HI_WORLD_AppMain
**
*/
void HI_WORLD_AppMain(void)
{

   uint32 RunStatus = CFE_ES_RunStatus_APP_ERROR;
   
   CFE_EVS_Register(NULL, 0, CFE_EVS_NO_FILTER);

   if (InitApp() == CFE_SUCCESS)      /* Performs initial CFE_ES_PerfLogEntry() call */
   {
      RunStatus = CFE_ES_RunStatus_APP_RUN; 
   }
   
   /*
   ** Main process loop
   */
   while (CFE_ES_RunLoop(&RunStatus))
   {
      if (sock < 0) {
          sock = socket(AF_INET, SOCK_DGRAM, 0);
          if (sock < 0) {
              CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_ERROR, "UDP Socket Creation Failed: %s", strerror(errno));
              return;
          }
      }
            
      ssize_t bytes_received;      
      uint8_t buffer[CCSDS_PACKET_MAX_SIZE];
      while ((bytes_received = recv(sock, buffer, sizeof(buffer), 0)) > 0) {
          ExtractDataFromBuffer(buffer, bytes_received);
      }

      
      RunStatus = ProcessCommands();  /* Pends indefinitely & manages CFE_ES_PerfLogEntry() calls */
      
      if (setParamTemp != Hi_world.SetParamCmdVal && setParamTemp != 0xFFFF) {
          SendOBDHCommand(Hi_world.SetParamCmdVal);
      }
      setParamTemp = Hi_world.SetParamCmdVal;
      
   } /* End CFE_ES_RunLoop */

   CFE_ES_WriteToSysLog("HI_WORLD App terminating, run status = 0x%08X\n", RunStatus);   /* Use SysLog, events may not be working */

   CFE_EVS_SendEvent(HI_WORLD_EXIT_EID, CFE_EVS_EventType_CRITICAL, "HI_WORLD App terminating, run status = 0x%08X", RunStatus);

   CFE_ES_ExitApp(RunStatus);  /* Let cFE kill the task (and any child tasks) */

} /* End of HI_WORLD_AppMain() */

void SendOBDHCommand(uint16_t payload_value)
{
    CCSDS_Packet_t *packet = (CCSDS_Packet_t *)malloc(sizeof(CCSDS_Packet_t));  
    if (packet == NULL) {
        perror("Memory allocation failed");
        return;
    }

    // Clear the packet structure
    memset(packet, 0, sizeof(CCSDS_Packet_t));

    // Packet version (3 bits) = 000, Packet type (1 bit) = 0, Secondary header flag (1 bit) = 0
    packet->header[0] = 0x00;

    // Set APID (11 bits) = 0x1AB
    packet->header[0] |= (0x1AB >> 8) & 0x07;  // APID upper 3 bits
    packet->header[1] = (0x1AB & 0xFF);        // APID lower 8 bits

    // Set sequence flags (2 bits) = 00 (continuation) and sequence count (14 bits) = 1
    packet->header[2] = 0x00;  // Sequence flags = 00, upper 6 bits of sequence count
    packet->header[3] = 0x01;  // Lower 8 bits of sequence count

    // Packet Data Length = (payload size - 1) = (2 - 1) = 1
    packet->header[4] = 0x00;  // Upper byte of length
    packet->header[5] = 0x01;  // Lower byte of length

    // Set the payload (Hi_world.SetParamCmdVal)
    packet->payload[0] = (payload_value >> 8) & 0xFF;  // High byte
    packet->payload[1] = payload_value & 0xFF;         // Low byte

    // Send the packet
    ssize_t bytes_sent = sendto(sock, packet, sizeof(CCSDS_Packet_t),
                                0, (struct sockaddr*)&clientAddr, sizeof(clientAddr));

    if (bytes_sent < 0) {
        perror("UDP CCSDS packet not sent");
    } else {
        printf("Sent CCSDS packet with param: 0x%04X", payload_value);
    }

    // Free memory
    free(packet);
}



void ExtractDataFromBuffer(uint8_t *buffer, ssize_t bytes_received) {
    uint16_t HeaderSize = CCSDS_PRIMARY_HEADER_SIZE;
    uint8_t *data_ptr;
    uint16_t category = 0;
    uint8_t sensor1BytesLong;
    uint16_t sensor2BytesLong;
    uint32_t sensor4BytesLong;

    if (bytes_received > HeaderSize) {
        data_ptr = buffer + HeaderSize;  // Skip past the primary header
        
        // Extract the first 2 bytes for the category (uint16_t)
        category = (data_ptr[0] << 8) | data_ptr[1];  // Combine the 2 bytes into uint16_t

        // Print the category for verification
        //CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_INFORMATION, "Category: 0x%04X", category);

        // Extract the remaining bytes for the sensor data
        uint16_t sensor_data_length = bytes_received - HeaderSize - 2;  // Remaining data length
        
        //CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_INFORMATION, "Sensor Data (sensor_data_length:%d) : ",sensor_data_length);
        switch (sensor_data_length) {
        case 0:
            //category
            break;
        case 1:
            sensor1BytesLong = data_ptr[2];
            //CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_INFORMATION, "sensor1BytesLong : 0x%02X", sensor1BytesLong);
            break;
        case 2:
            sensor2BytesLong = (data_ptr[2] << 8) | data_ptr[3];
            //CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_INFORMATION, "sensor2BytesLong : 0x%04X", sensor2BytesLong);
            break;
        case 4:
            sensor4BytesLong = (data_ptr[2] << 24) | (data_ptr[3] << 16) | (data_ptr[4] << 8) | data_ptr[5];
            //CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_INFORMATION, "sensor4BytesLong : 0x%08X", sensor4BytesLong);
            break;
        default:
            CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_ERROR, "Unknown sensor_data_length : %d", sensor_data_length);
            break;
        }

        if (category >= 0x0000 && category <= 0x00FF)
                Hi_world.OBDHStatus = category;
        else if (category >= 0x0700 && category <= 0x07FF)
                Hi_world.OBDHMainState = category;
        else if (category >= 0x0E00 && category <= 0x0EFF)
                Hi_world.OBDHError = category;
        else if (category >= 0x1000 && category <= 0x10FF)
                Hi_world.PayloadStatus = category;
        else if (category >= 0x1700 && category <= 0x17FF)
                Hi_world.PayloadMainState = category;
        else if (category >= 0x1E00 && category <= 0x1EFF)
                Hi_world.PayloadError = category;
        else if (category >= 0x2000 && category <= 0x20FF)
                Hi_world.EPSStatus = category;
        else if (category >= 0x2700 && category <= 0x27FF)
                Hi_world.EPSMainState = category;
        else if (category >= 0x2E00 && category <= 0x2EFF)
                Hi_world.EPSError = category;
        else {
            switch (category) {
            case 0x0900:
                Hi_world.sensor1 = sensor1BytesLong;
                break;
            case 0x0901:
                Hi_world.sensor2 = sensor2BytesLong;
                break;
            case 0x0902:
                Hi_world.sensor3 = sensor4BytesLong;
                break;
            default:
                CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_ERROR, "Unknown category 0x%04X", category);
                break;
            }
        }
    }
    else {
        CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_ERROR, "Payload size is smaller than expected.");
    }
}

void OBDH_Telem_InitUDP(void) {
    struct sockaddr_in serv_addr;
    
    if (sock < 0) {
        sock = socket(AF_INET, SOCK_DGRAM, 0);
        if (sock < 0) {
            CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_ERROR, "UDP Socket Creation Failed: %s", strerror(errno));
            return;
        }
        
        // Set to non-blocking mode
        int flags = fcntl(sock, F_GETFL, 0);
        if (flags != -1) {
            fcntl(sock, F_SETFL, flags | O_NONBLOCK);
        }

        CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_INFORMATION, "UDP Socket Created!");
    }

    memset(&serv_addr, 0, sizeof(serv_addr));
    serv_addr.sin_family = AF_INET;
    serv_addr.sin_addr.s_addr = INADDR_ANY;
    serv_addr.sin_port = htons(OBDH_TELEM_UDP_PORT);

    if (bind(sock, (struct sockaddr*)&serv_addr, sizeof(serv_addr)) < 0) {
        CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_ERROR, "UDP Bind Failed: %s", strerror(errno));
        return;
    }

    CFE_EVS_SendEvent(HI_WORLD_NOOP_EID, CFE_EVS_EventType_INFORMATION, "UDP Socket Bound Successfully on Port %d", OBDH_TELEM_UDP_PORT);
}

void OBDH_TC_InitUDP(void) {
    // Setup the destination address (this is where the packet will be sent)
    memset(&clientAddr, 0, sizeof(clientAddr));
    clientAddr.sin_family = AF_INET;
    clientAddr.sin_port = htons(OBDH_TC_UDP_PORT);  // Destination port
    clientAddr.sin_addr.s_addr = inet_addr(OBDH_IP_ADDRESS);  // Destination IP address (localhost, change to actual IP)
}



/******************************************************************************
** Function: HI_WORLD_NoOpCmd
**
*/
bool HI_WORLD_NoOpCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr)
{

   CFE_EVS_SendEvent (HI_WORLD_NOOP_EID, CFE_EVS_EventType_INFORMATION,
                      "No operation command received for HI_WORLD App version %d.%d.%d",
                      HI_WORLD_MAJOR_VER, HI_WORLD_MINOR_VER, HI_WORLD_PLATFORM_REV);

   return true;


} /* End HI_WORLD_NoOpCmd() */


/******************************************************************************
** Function: HI_WORLD_ResetAppCmd
**
** Notes:
**   1. Framework objects require an object reference since they are
**      reentrant. Applications use the singleton pattern and store a
**      reference pointer to the object data during construction.
*/
bool HI_WORLD_ResetAppCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr)
{

   CMDMGR_ResetStatus(CMDMGR_OBJ);
     
   return true;

} /* End HI_WORLD_ResetAppCmd() */


/******************************************************************************
** Function: HI_WORLD_SetParamCmd
**
** Notes:
**   1. HI_WORLD_SetParamCmd_Payload_t and HI_WORLD_SetParamCmd_t
**      are generated from the EDS file hi_world.xml
**   2. CMDMGR_PAYLOAD_PTR is a macro defined by app_c_fw's cmdmgr component
**      that returns a pointer to the payload structure and it inforces the
**      the 'Payload' naming convention. 
*/

bool HI_WORLD_SetParamCmd(void* ObjDataPtr, const CFE_MSG_Message_t *MsgPtr)
{
   const HI_WORLD_SetParam_CmdPayload_t *CmdPayload = CMDMGR_PAYLOAD_PTR(MsgPtr, HI_WORLD_SetParam_t);
   
   CFE_EVS_SendEvent (HI_WORLD_SET_PARAM_EID, CFE_EVS_EventType_INFORMATION,
                      "Set Parameter commmand received a parameter value %d",
                      CmdPayload->Param);

   Hi_world.SetParamCmdVal = CmdPayload->Param;

   return true;


} /* End HI_WORLD_SetParamCmd() */


/******************************************************************************
** Function: InitApp
**
*/
static int32 InitApp(void)
{

   int32 Status = APP_C_FW_CFS_ERROR;
   

   /*
   ** Initialize objects 
   */
   
   if (INITBL_Constructor(INITBL_OBJ, HI_WORLD_INI_FILENAME, &IniCfgEnum))
   {
   
      Hi_world.PerfId  = INITBL_GetIntConfig(INITBL_OBJ, CFG_APP_PERF_ID);
      CFE_ES_PerfLogEntry(Hi_world.PerfId);

      Hi_world.CmdMid         = CFE_SB_ValueToMsgId(INITBL_GetIntConfig(INITBL_OBJ, CFG_HI_WORLD_CMD_TOPICID));
      Hi_world.SendStatusMid  = CFE_SB_ValueToMsgId(INITBL_GetIntConfig(INITBL_OBJ, CFG_HI_WORLD_SEND_STATUS_TOPICID));
      
      /*
      ** Constuct app's contained objects
      */
            
      
      /*
      ** Initialize app level interfaces
      */
      
      CFE_SB_CreatePipe(&Hi_world.CmdPipe, INITBL_GetIntConfig(INITBL_OBJ, CFG_APP_CMD_PIPE_MAX), INITBL_GetStrConfig(INITBL_OBJ, CFG_APP_CMD_PIPE_NAME));  
      CFE_SB_Subscribe(Hi_world.CmdMid,        Hi_world.CmdPipe);
      CFE_SB_Subscribe(Hi_world.SendStatusMid, Hi_world.CmdPipe);

      CMDMGR_Constructor(CMDMGR_OBJ);
      CMDMGR_RegisterFunc(CMDMGR_OBJ, HI_WORLD_NOOP_CC,  NULL, HI_WORLD_NoOpCmd,     0);
      CMDMGR_RegisterFunc(CMDMGR_OBJ, HI_WORLD_RESET_CC, NULL, HI_WORLD_ResetAppCmd, 0);      
      CMDMGR_RegisterFunc(CMDMGR_OBJ, HI_WORLD_SET_PARAM_CC, NULL, HI_WORLD_SetParamCmd, sizeof(HI_WORLD_SetParam_CmdPayload_t));

      /*
      ** Initialize app messages 
      */

      CFE_MSG_Init(CFE_MSG_PTR(Hi_world.StatusTlm.TelemetryHeader), 
                   CFE_SB_ValueToMsgId(INITBL_GetIntConfig(INITBL_OBJ, CFG_HI_WORLD_STATUS_TLM_TOPICID)),
                   sizeof(HI_WORLD_StatusTlm_t));

      /*
      ** Application startup event message
      */
      CFE_EVS_SendEvent(HI_WORLD_INIT_APP_EID, CFE_EVS_EventType_INFORMATION,
                        "HI_WORLD App Initialized. Version %d.%d.%d",
                        HI_WORLD_MAJOR_VER, HI_WORLD_MINOR_VER, HI_WORLD_PLATFORM_REV);
                        
                        
      OBDH_Telem_InitUDP();
      OBDH_TC_InitUDP();

      Status = CFE_SUCCESS; 

   } /* End if INITBL constructed */
   
   return(Status);

} /* End of InitApp() */


/******************************************************************************
** Function: ProcessCommands
**
** 
*/
static int32 ProcessCommands(void)
{
   
   int32  RetStatus = CFE_ES_RunStatus_APP_RUN;
   int32  SysStatus;

   CFE_SB_Buffer_t  *SbBufPtr;
   CFE_SB_MsgId_t   MsgId = CFE_SB_INVALID_MSG_ID;

   CFE_ES_PerfLogExit(Hi_world.PerfId);
   SysStatus = CFE_SB_ReceiveBuffer(&SbBufPtr, Hi_world.CmdPipe, CFE_SB_PEND_FOREVER);
   CFE_ES_PerfLogEntry(Hi_world.PerfId);

   if (SysStatus == CFE_SUCCESS)
   {
      SysStatus = CFE_MSG_GetMsgId(&SbBufPtr->Msg, &MsgId);

      if (SysStatus == CFE_SUCCESS)
      {

         if (CFE_SB_MsgId_Equal(MsgId, Hi_world.CmdMid))
         {
            CMDMGR_DispatchFunc(CMDMGR_OBJ, &SbBufPtr->Msg);
         } 
         else if (CFE_SB_MsgId_Equal(MsgId, Hi_world.SendStatusMid))
         {   
            SendStatusTlm();
         }
         else
         {   
            CFE_EVS_SendEvent(HI_WORLD_INVALID_MID_EID, CFE_EVS_EventType_ERROR,
                              "Received invalid command packet, MID = 0x%08X", 
                              CFE_SB_MsgIdToValue(MsgId));
         }

      } /* End if got message ID */
   } /* End if received buffer */
   else
   {
      RetStatus = CFE_ES_RunStatus_APP_ERROR;
   } 

   return RetStatus;
   
} /* End ProcessCommands() */


/******************************************************************************
** Function: SendStatusTlm
**
*/
static void SendStatusTlm(void)
{

   HI_WORLD_StatusTlm_Payload_t *Payload = &Hi_world.StatusTlm.Payload;

   /*
   ** Framework Data
   */
   
   Payload->ValidCmdCnt   = Hi_world.CmdMgr.ValidCmdCnt;
   Payload->InvalidCmdCnt = Hi_world.CmdMgr.InvalidCmdCnt;
   Payload->SetParamCmdVal = Hi_world.SetParamCmdVal;
   Payload->OBDHStatus = Hi_world.OBDHStatus;
   Payload->OBDHMainState = Hi_world.OBDHMainState;
   Payload->OBDHError = Hi_world.OBDHError;
   Payload->PayloadStatus = Hi_world.PayloadStatus;
   Payload->PayloadMainState = Hi_world.PayloadMainState;
   Payload->PayloadError = Hi_world.PayloadError;
   Payload->EPSStatus = Hi_world.EPSStatus;
   Payload->OBDHStatus = Hi_world.EPSMainState;
   Payload->OBDHStatus = Hi_world.EPSError;
   Payload->sensor1 = Hi_world.sensor1;
   Payload->sensor2 = Hi_world.sensor2;
   Payload->sensor3 = Hi_world.sensor3;
   
   CFE_SB_TimeStampMsg(CFE_MSG_PTR(Hi_world.StatusTlm.TelemetryHeader));
   CFE_SB_TransmitMsg(CFE_MSG_PTR(Hi_world.StatusTlm.TelemetryHeader), true);

} /* End SendStatusTlm() */
