/*
**  Copyright 2022 bitValence, Inc.
**  All Rights Reserved.
**
**  This program is free software; you can modify and/or redistribute it
**  under the terms of the GNU Affero General Public License
**  as published by the Free Software Foundation; version 3 with
**  attribution addendums as found in the LICENSE.txt
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU Affero General Public License for more details.
**
**  Purpose:
**    Implement the Hi_world application
**
**  Notes:
**   1. This file was automatically generated by cFS Basecamp's app
**      creation tool. If you edit it, your changes will be lost if
**      a new app with the same name is created. 
**
*/


/*
** Includes
*/

#include <string.h>
#include "hi_world_app.h"
#include "hi_world_eds_cc.h"

/***********************/
/** Macro Definitions **/
/***********************/

/* Convenience macros */
#define  INITBL_OBJ    (&(Hi_world.IniTbl))
#define  CMDMGR_OBJ    (&(Hi_world.CmdMgr))


/*******************************/
/** Local Function Prototypes **/
/*******************************/

static int32 InitApp(void);
static int32 ProcessCommands(void);
static void SendStatusTlm(void);


/**********************/
/** File Global Data **/
/**********************/

/* 
** Must match DECLARE ENUM() declaration in app_cfg.h
** Defines "static INILIB_CfgEnum_t IniCfgEnum"
*/
DEFINE_ENUM(Config,APP_CONFIG)  


/*****************/
/** Global Data **/
/*****************/

HI_WORLD_Class_t  Hi_world;


/******************************************************************************
** Function: HI_WORLD_AppMain
**
*/
void HI_WORLD_AppMain(void)
{

   uint32 RunStatus = CFE_ES_RunStatus_APP_ERROR;
   
   CFE_EVS_Register(NULL, 0, CFE_EVS_NO_FILTER);

   if (InitApp() == CFE_SUCCESS)      /* Performs initial CFE_ES_PerfLogEntry() call */
   {
      RunStatus = CFE_ES_RunStatus_APP_RUN; 
   }
   
   /*
   ** Main process loop
   */
   while (CFE_ES_RunLoop(&RunStatus))
   {
      
      RunStatus = ProcessCommands();  /* Pends indefinitely & manages CFE_ES_PerfLogEntry() calls */
      
   } /* End CFE_ES_RunLoop */

   CFE_ES_WriteToSysLog("HI_WORLD App terminating, run status = 0x%08X\n", RunStatus);   /* Use SysLog, events may not be working */

   CFE_EVS_SendEvent(HI_WORLD_EXIT_EID, CFE_EVS_EventType_CRITICAL, "HI_WORLD App terminating, run status = 0x%08X", RunStatus);

   CFE_ES_ExitApp(RunStatus);  /* Let cFE kill the task (and any child tasks) */

} /* End of HI_WORLD_AppMain() */


/******************************************************************************
** Function: HI_WORLD_NoOpCmd
**
*/
bool HI_WORLD_NoOpCmd(void* ObjDataPtr, const CFE_MSG_Message_t *MsgPtr)
{

   CFE_EVS_SendEvent (HI_WORLD_NOOP_EID, CFE_EVS_EventType_INFORMATION,
                      "No operation command received for HI_WORLD App version %d.%d.%d",
                      HI_WORLD_MAJOR_VER, HI_WORLD_MINOR_VER, HI_WORLD_PLATFORM_REV);

   return true;


} /* End HI_WORLD_NoOpCmd() */


//EX1
/******************************************************************************
** Function: HI_WORLD_ResetAppCmd
**
** Notes:
**   1. Framework objects require an object reference since they are
**      reentrant. Applications use the singleton pattern and store a
**      reference pointer to the object data during construction.
*/
bool HI_WORLD_ResetAppCmd(void* ObjDataPtr, const CFE_MSG_Message_t *MsgPtr)
{

   CMDMGR_ResetStatus(CMDMGR_OBJ);
     
   return true;

} /* End HI_WORLD_ResetAppCmd() */

/******************************************************************************
** Function: HI_WORLD_SetParamCmd
**
** Notes:
**   1. HI_WORLD_SetParamCmd_Payload_t and HI_WORLD_SetParamCmd_t
**      are generated from the EDS file hi_world.xml
**   2. CMDMGR_PAYLOAD_PTR is a macro defined by app_c_fw's cmdmgr component
**      that returns a pointer to the payload structure and it inforces the
**      the 'Payload' naming convention. 
*/
bool HI_WORLD_SetParamCmd(void* ObjDataPtr, const CFE_MSG_Message_t *MsgPtr)
{
   const HI_WORLD_SetParam_CmdPayload_t *CmdPayload = CMDMGR_PAYLOAD_PTR(MsgPtr, HI_WORLD_SetParam_t);
   
   CFE_EVS_SendEvent (HI_WORLD_SET_PARAM_EID, CFE_EVS_EventType_INFORMATION,
                      "Set Parameter commmand received a parameter value %d",
                      CmdPayload->Param);

   return true;


} /* End HI_WORLD_SetParamCmd() */
//EX1


/******************************************************************************
** Function: InitApp
**
*/
static int32 InitApp(void)
{

   int32 Status = APP_C_FW_CFS_ERROR;
   

   /*
   ** Initialize objects 
   */
   
   if (INITBL_Constructor(INITBL_OBJ, HI_WORLD_INI_FILENAME, &IniCfgEnum))
   {
   
      Hi_world.PerfId  = INITBL_GetIntConfig(INITBL_OBJ, CFG_APP_PERF_ID);
      CFE_ES_PerfLogEntry(Hi_world.PerfId);

      Hi_world.CmdMid         = CFE_SB_ValueToMsgId(INITBL_GetIntConfig(INITBL_OBJ, CFG_HI_WORLD_CMD_TOPICID));
      Hi_world.SendStatusMid  = CFE_SB_ValueToMsgId(INITBL_GetIntConfig(INITBL_OBJ, CFG_HI_WORLD_SEND_STATUS_TOPICID));
      
      /*
      ** Constuct app's contained objects
      */
            
      
      /*
      ** Initialize app level interfaces
      */
      
      CFE_SB_CreatePipe(&Hi_world.CmdPipe, INITBL_GetIntConfig(INITBL_OBJ, CFG_APP_CMD_PIPE_DEPTH), INITBL_GetStrConfig(INITBL_OBJ, CFG_APP_CMD_PIPE_NAME));  
      CFE_SB_Subscribe(Hi_world.CmdMid,        Hi_world.CmdPipe);
      CFE_SB_Subscribe(Hi_world.SendStatusMid, Hi_world.CmdPipe);

      //EX2
      CMDMGR_Constructor(CMDMGR_OBJ);
      CMDMGR_RegisterFunc(CMDMGR_OBJ, HI_WORLD_NOOP_CC,      NULL, HI_WORLD_NoOpCmd,     0);
      CMDMGR_RegisterFunc(CMDMGR_OBJ, HI_WORLD_RESET_CC,     NULL, HI_WORLD_ResetAppCmd, 0);
      CMDMGR_RegisterFunc(CMDMGR_OBJ, HI_WORLD_SET_PARAM_CC, NULL, HI_WORLD_SetParamCmd, sizeof(HI_WORLD_SetParam_CmdPayload_t));
      //EX2
      
      /*
      ** Initialize app messages 
      */

      CFE_MSG_Init(CFE_MSG_PTR(Hi_world.StatusTlm.TelemetryHeader), 
                   CFE_SB_ValueToMsgId(INITBL_GetIntConfig(INITBL_OBJ, CFG_HI_WORLD_STATUS_TLM_TOPICID)),
                   sizeof(HI_WORLD_StatusTlm_t));

      /*
      ** Application startup event message
      */
      CFE_EVS_SendEvent(HI_WORLD_INIT_APP_EID, CFE_EVS_EventType_INFORMATION,
                        "HI_WORLD App Initialized. Version %d.%d.%d",
                        HI_WORLD_MAJOR_VER, HI_WORLD_MINOR_VER, HI_WORLD_PLATFORM_REV);

      Status = CFE_SUCCESS; 

   } /* End if INITBL constructed */
   
   return(Status);

} /* End of InitApp() */


/******************************************************************************
** Function: ProcessCommands
**
** 
*/
static int32 ProcessCommands(void)
{
   
   int32  RetStatus = CFE_ES_RunStatus_APP_RUN;
   int32  SysStatus;

   CFE_SB_Buffer_t  *SbBufPtr;
   CFE_SB_MsgId_t   MsgId = CFE_SB_INVALID_MSG_ID;


   CFE_ES_PerfLogExit(Hi_world.PerfId);
   SysStatus = CFE_SB_ReceiveBuffer(&SbBufPtr, Hi_world.CmdPipe, CFE_SB_PEND_FOREVER);
   CFE_ES_PerfLogEntry(Hi_world.PerfId);

   if (SysStatus == CFE_SUCCESS)
   {
      SysStatus = CFE_MSG_GetMsgId(&SbBufPtr->Msg, &MsgId);

      if (SysStatus == CFE_SUCCESS)
      {

         if (CFE_SB_MsgId_Equal(MsgId, Hi_world.CmdMid))
         {
            CMDMGR_DispatchFunc(CMDMGR_OBJ, &SbBufPtr->Msg);
         } 
         else if (CFE_SB_MsgId_Equal(MsgId, Hi_world.SendStatusMid))
         {   
            SendStatusTlm();
         }
         else
         {   
            CFE_EVS_SendEvent(HI_WORLD_INVALID_MID_EID, CFE_EVS_EventType_ERROR,
                              "Received invalid command packet, MID = 0x%08X", 
                              CFE_SB_MsgIdToValue(MsgId));
         }

      } /* End if got message ID */
   } /* End if received buffer */
   else
   {
      RetStatus = CFE_ES_RunStatus_APP_ERROR;
   } 

   return RetStatus;
   
} /* End ProcessCommands() */


/******************************************************************************
** Function: SendStatusTlm
**
*/
static void SendStatusTlm(void)
{

   HI_WORLD_StatusTlm_Payload_t *Payload = &Hi_world.StatusTlm.Payload;

   /*
   ** Framework Data
   */
   
   Payload->ValidCmdCnt   = Hi_world.CmdMgr.ValidCmdCnt;
   Payload->InvalidCmdCnt = Hi_world.CmdMgr.InvalidCmdCnt;
   
   CFE_SB_TimeStampMsg(CFE_MSG_PTR(Hi_world.StatusTlm.TelemetryHeader));
   CFE_SB_TransmitMsg(CFE_MSG_PTR(Hi_world.StatusTlm.TelemetryHeader), true);

} /* End SendStatusTlm() */

