/*
**  Copyright 2022 bitValence, Inc.
**  All Rights Reserved.
**
**  This program is free software; you can modify and/or redistribute it
**  under the terms of the GNU Affero General Public License
**  as published by the Free Software Foundation; version 3 with
**  attribution addendums as found in the LICENSE.txt
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU Affero General Public License for more details.
**
**  Purpose:
**    Define the Hi_world application
**
**  Notes:
**   1. This file was automatically generated by cFS Basecamp's app
**      creation tool. If you edit it, your changes will be lost if
**      a new app with the same name is created. 
**
*/

#ifndef _hi_world_app_
#define _hi_world_app_

/*
** Includes
*/

#include "app_cfg.h"

/***********************/
/** Macro Definitions **/
/***********************/

//EX1
/*
** Events
*/

#define HI_WORLD_INIT_APP_EID    (HI_WORLD_BASE_EID + 0)
#define HI_WORLD_NOOP_EID        (HI_WORLD_BASE_EID + 1)
#define HI_WORLD_EXIT_EID        (HI_WORLD_BASE_EID + 2)
#define HI_WORLD_INVALID_MID_EID (HI_WORLD_BASE_EID + 3)
#define HI_WORLD_SET_PARAM_EID   (HI_WORLD_BASE_EID + 4)
//EX1

/**********************/
/** Type Definitions **/
/**********************/


/******************************************************************************
** Command Packets
** - See EDS command definitions in hi_world.xml
*/


/******************************************************************************
** Telmetery Packets
** - See EDS command definitions in hi_world.xml
*/


/******************************************************************************
** HI_WORLD_Class
*/
typedef struct
{

   /* 
   ** App Framework
   */ 
    
   INITBL_Class_t  IniTbl; 
   CMDMGR_Class_t  CmdMgr;
   
   /*
   ** Command Packets
   */

 
   /*
   ** Telemetry Packets
   */
   
   HI_WORLD_StatusTlm_t  StatusTlm;
   
   /*
   ** HI_WORLD State & Contained Objects
   */ 
           
   uint32           PerfId;
   CFE_SB_PipeId_t  CmdPipe;
   CFE_SB_MsgId_t   CmdMid;
   CFE_SB_MsgId_t   SendStatusMid;
   
} HI_WORLD_Class_t;


/*******************/
/** Exported Data **/
/*******************/

extern HI_WORLD_Class_t  Hi_world;


/************************/
/** Exported Functions **/
/************************/


/******************************************************************************
** Function: HI_WORLD_AppMain
**
*/
void HI_WORLD_AppMain(void);


/******************************************************************************
** Function: HI_WORLD_NoOpCmd
**
*/
bool HI_WORLD_NoOpCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);


//EX2
/******************************************************************************
** Function: HI_WORLD_ResetAppCmd
**
*/
bool HI_WORLD_ResetAppCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);



/******************************************************************************
** Function: HI_WORLD_SetParam
**
*/
bool HI_WORLD_SetParamCmd(void *ObjDataPtr, const CFE_MSG_Message_t *MsgPtr);
//EX2

#endif /* _hi_world_ */
