M48
; DRILL file {KiCad 8.0.8} date 2025-02-25T18:25:48+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-25T18:25:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.180
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C6.500
%
G90
G05
T1
X156.95Y-134.54
X181.95Y-134.54
T2
X42.5Y-51.5
X42.5Y-138.25
X230.5Y-51.5
X230.5Y-132.29
T3
X42.627Y-67.5
X60.122Y-78.75
X63.75Y-88.377
X83.127Y-117.0
M30
