/*
**  Copyright 2022 bitValence, Inc.
**  All Rights Reserved.
**
**  This program is free software; you can modify and/or redistribute it
**  under the terms of the GNU Affero General Public License
**  as published by the Free Software Foundation; version 3 with
**  attribution addendums as found in the LICENSE.txt
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU Affero General Public License for more details.
**
**  Purpose:
**    Define configurations for the Hi_world application
**
**  Notes:
**   1. This file was automatically generated by cFS Basecamp's app
**      creation tool. If you edit it, your changes will be lost if
**      a new app with the same name is created. 
**   2. Compile-time configurations that are applied to all platform
**      deployments of this app for a mission.
**   3. These definitions should be minimal and only contain parameters that
**      need to be configurable for a mission and that must be defined at
**      compile time. Use hi_world_platform_cfg.h for compile-time
**      parameters that can be tuned for each platform deployment. Use
**      app_cfg.h for compile-time parameters that don't need to be
**      configured when an app is deployed but are useful to be parameterized
**      for maintaining the app and use the JSON initialization file for
**      parameters that can be defined at runtime.
**
*/
#ifndef _hi_world_mission_cfg_
#define _hi_world_mission_cfg_


#endif /* _hi_world_mission_cfg_ */
